//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/ChangeMode.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ChangeMode : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ChangeMode()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ChangeMode"",
    ""maps"": [
        {
            ""name"": ""Mode"",
            ""id"": ""14b78dc2-c996-42a5-b613-56b31310dc7a"",
            ""actions"": [
                {
                    ""name"": ""Change"",
                    ""type"": ""Button"",
                    ""id"": ""a3ec1dd0-79e1-45da-8067-27bcc65f3840"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""30386757-3bb3-4cee-ac84-8f192828819c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Mode
        m_Mode = asset.FindActionMap("Mode", throwIfNotFound: true);
        m_Mode_Change = m_Mode.FindAction("Change", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mode
    private readonly InputActionMap m_Mode;
    private IModeActions m_ModeActionsCallbackInterface;
    private readonly InputAction m_Mode_Change;
    public struct ModeActions
    {
        private @ChangeMode m_Wrapper;
        public ModeActions(@ChangeMode wrapper) { m_Wrapper = wrapper; }
        public InputAction @Change => m_Wrapper.m_Mode_Change;
        public InputActionMap Get() { return m_Wrapper.m_Mode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ModeActions set) { return set.Get(); }
        public void SetCallbacks(IModeActions instance)
        {
            if (m_Wrapper.m_ModeActionsCallbackInterface != null)
            {
                @Change.started -= m_Wrapper.m_ModeActionsCallbackInterface.OnChange;
                @Change.performed -= m_Wrapper.m_ModeActionsCallbackInterface.OnChange;
                @Change.canceled -= m_Wrapper.m_ModeActionsCallbackInterface.OnChange;
            }
            m_Wrapper.m_ModeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Change.started += instance.OnChange;
                @Change.performed += instance.OnChange;
                @Change.canceled += instance.OnChange;
            }
        }
    }
    public ModeActions @Mode => new ModeActions(this);
    public interface IModeActions
    {
        void OnChange(InputAction.CallbackContext context);
    }
}
